version: "3"
services:
  zip_geosearch:
    container_name: zip_geosearch
    image: docker.pkg.github.com/cbacon93/zip_geosearch/zip_geosearch
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017/
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db
